name: CI-CD

on:
  push:
    branches: [main, devops]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r backend/requirements.txt pytest
      - name: Run tests
        run: pytest
        working-directory: backend
      - name: Build Docker image
        run: docker build -t cloudpulse .